### ISSUE TITLE
Can't get data over stdout

### ISSUE THREAD

**Issue by OvermindDL1** [devstopfix/gnuplot-elixir#18]
The default `set output` result is to print to `STDOUT`, however as seen on:  https://github.com/devstopfix/gnuplot-elixir/blob/master/lib/gnuplot.ex#L64
```elixir
    {:ok, cmd}
```
The `plot` command returns the command executed for some reason, instead of the actual output of the program.  The command executed is useless, the program output is useful, yet I cannot seem to see a way in the source to get the program output.  In short I'm not able to see how to use this on a headless write-only system...  What am I missing?

**Comment by devstopfix** [comment]
Apologies - I just saw this message @OvermindDL1

**Comment by devstopfix** [comment]
@OvermindDL1 I am working on returning the output of gnuplot should the plot fail (e.g. invalid commands). Is this enough - can you clarify what you mean by _headless write-only system_ ?  Thank you!

**Comment by devstopfix** [comment]
For a headless system, you just write the chart to a file (perhaps a temporary file) :

```
[:set, :term, :pngcairo],
  [:set, :output, "/tmp/rand.png"]
```

Should the command fail, the errors are in stdout, I am working on a PR that will make them available to the caller.
