### ISSUE TITLE
Bug in default timeout value

### ISSUE THREAD

**Issue by carusso** [devstopfix/gnuplot-elixir#25]
Line 78 of gnuplot.ex is this:
{t, :ms} = Application.get_env(:gnuplot, :timeout, 10_000)

That default of 10_000 fails to match the tuple on the left-hand side.

Code fix would be:
{t, :ms} = Application.get_env(:gnuplot, :timeout, {10_000, :ms})

**Comment by zevv** [comment]
Workaround until this is fixed, put the following in your own config.exs:

```
config :gnuplot,
  timeout: { 10_000, :ms}
```

**Comment by devstopfix** [comment]
Thanks this was fixed in 4e77d9 but possibly not pushed to hex. Will do so now.

**Comment by devstopfix** [comment]
Thanks @carusso and @zevv - this fix has been pushed to hex.
